baseURL = 'https://si40code.github.io/notes/'
languageCode = 'zh-cn'
title = 'Notes'
theme = 'notes-theme'
paginate = 10

# SEO配置
enableRobotsTXT = true
enableGitInfo = true

[params]
  description = '记录随笔与学习笔记'
  author = 'Si40Code'
  keywords = ['博客', '笔记', '技术', '学习', '随笔']
  
  # SEO相关
  [params.seo]
    googleAnalytics = ""  # 如果需要可以添加GA ID
    googleSiteVerification = ""  # Google Search Console验证码
