baseURL = 'https://si40code.github.io/notes/'
languageCode = 'zh-cn'
title = 'Notes'
theme = 'notes-theme'
paginate = 10

# SEO配置
enableRobotsTXT = true
enableGitInfo = true

# Sitemap配置
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# 输出格式配置
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 菜单配置
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2

[params]
  description = '记录随笔与学习笔记 - Si40Code的技术博客'
  author = 'Si40Code'
  keywords = ['博客', '笔记', '技术', '学习', '随笔', 'Hugo', 'Web开发']
  
  # SEO相关
  [params.seo]
    googleAnalytics = ""  # 如果需要可以添加GA ID
    googleSiteVerification = "m_FerUXyd1Cyy4_h32-u83yW3I3d-cEzRDRRqQ6bwbk"  # Google Search Console验证码
    twitterCard = "summary_large_image"
    twitterSite = ""  # 如果有Twitter账号
    
  # 社交媒体配置
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/si40code"
  # 如果有其他社交媒体账号，可以添加更多
  # [[params.social]]
  #   name = "Twitter"
  #   url = "https://twitter.com/yourusername"
  # [[params.social]]
  #   name = "Email"
  #   url = "mailto:your@email.com"
